module DarkSky
  module Languages
    Arabic             = "ar"
    Azerbaijani        = "az"
    Belarusian         = "be"
    Bosnian            = "bs"
    Catalan            = "ca"
    Czech              = "cs"
    German             = "de"
    Greek              = "el"
    English            = "en"
    Spanish            = "es"
    Estonian           = "et"
    French             = "fr"
    Croatian           = "hr"
    Hungarian          = "hu"
    Indonesian         = "id"
    Italian            = "it"
    Icelandic          = "is"
    Cornish            = "kw"
    Indonesia          = "nb"
    Dutch              = "nl"
    Polish             = "pl"
    Portuguese         = "pt"
    Russian            = "ru"
    Slovak             = "sk"
    Slovenian          = "sl"
    Serbian            = "sr"
    Swedish            = "sv"
    Tetum              = "te"
    Turkish            = "tr"
    Ukrainian          = "uk"
    IgpayAtinlay       = "x-pig-latin"
    SimplifiedChinese  = "zh"
    TraditionalChinese = "zh-tw"
  end
end
